package states

const (
	STATE_MAIN int = iota
	STATE_EXIT
	STATE_UTILITIES
	STATE_WORKFLOW_LIST
	STATE_WORKFLOW_CONFIRM
	STATE_WORKFLOW_RUN
	STATE_WORKFLOW_FINISH
	STATE_WORKFLOW_FAIL
	STATE_WORKFLOW_HELP
	STATE_WORKFLOW_CMD
	STATE_WORKFLOW_CMDLIST

	STATE_COUNT
)
